### ISSUE TITLE
Tracking issue for small issues introduced pre-2.6

### ISSUE THREAD

**Issue by boehs** [boehs/boehs.github.io#34]
1. [x] Scroll position is janky – should scroll to top in some contexts
2. [x] 404 pages reloading triggers download
3. [x] 404 pages missing "what links here"
